services:
  pg:
    container_name: pg
    hostname: pg
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data

  web:
    container_name: grfc_backend
    build: 
      context: ./grfc_backend 
      dockerfile: Dockerfile 
    ports:
      - "8001:8001"
    depends_on:
      - pg

    env_file:
      - .env
