services:
  pg:
    container_name: pg
    hostname: pg
    image: postgres:latest
    networks:
      - net
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data

  web:
    container_name: grfc_backend
    networks:
      - net
    build: 
      context: ./grfc_backend 
      dockerfile: Dockerfile
    ports:
      - "8001:8001"

    volumes:
      - ./grfc_backend/static:/static

    depends_on:
      - pg

    env_file:
      - .env

  nginx:
    image: nginx
    restart: always
    networks:
      - net
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf/:ro
    - ./grfc_backend/static:/static/:ro
    - ./certbot/www:/var/www/certbot/:ro
    - ./certbot/conf/:/etc/nginx/ssl/:ro
    ports:
    - "80:80"
    - "443:443"
    depends_on:
    - web

  # certbot:
  #   image: certbot/certbot:latest
  #   networks:
  #     - net
  #   volumes:
  #     - ./certbot/www/:/var/www/certbot/:rw
  #     - ./certbot/conf/:/etc/letsencrypt/:rw

networks:
  net:
